### ISSUE TITLE
Zet metadata in de footer

### ISSUE THREAD

**Issue by JKoenen99** [dnlrsml/FeD2#3]
Artiest etc:
https://github.com/vasilisvg/blokweb-issues/blob/master/html/overzicht-html.md#elke-section-heeft-een-heading
https://github.com/dnlrsml/FeD2/blob/2927fceaa812e9ab22608d58c498ef0ecfe09570/index.html#L27

**Comment by dnlrsml** [comment]
oke top thnx aangepast
